/** Seeded once per account (flag `initialized:exercises`), editable afterwards. [name, muscle] */
export const DEFAULT_EXERCISES: readonly [string, string][] = [
  ['Bench Press', 'Chest'],
  ['Incline Dumbbell Press', 'Chest'],
  ['Chest Fly', 'Chest'],
  ['Push-up', 'Chest'],
  ['Dips', 'Chest'],
  ['Overhead Press', 'Shoulders'],
  ['Lateral Raise', 'Shoulders'],
  ['Rear Delt Fly', 'Shoulders'],
  ['Pull-up', 'Back'],
  ['Lat Pulldown', 'Back'],
  ['Barbell Row', 'Back'],
  ['Seated Cable Row', 'Back'],
  ['Dumbbell Row', 'Back'],
  ['Deadlift', 'Back'],
  ['Face Pull', 'Shoulders'],
  ['Barbell Curl', 'Biceps'],
  ['Dumbbell Curl', 'Biceps'],
  ['Hammer Curl', 'Biceps'],
  ['Triceps Pushdown', 'Triceps'],
  ['Overhead Triceps Extension', 'Triceps'],
  ['Skull Crusher', 'Triceps'],
  ['Squat', 'Legs'],
  ['Leg Press', 'Legs'],
  ['Romanian Deadlift', 'Legs'],
  ['Lunge', 'Legs'],
  ['Leg Extension', 'Legs'],
  ['Leg Curl', 'Legs'],
  ['Hip Thrust', 'Glutes'],
  ['Calf Raise', 'Calves'],
  ['Plank', 'Core'],
  ['Hanging Leg Raise', 'Core'],
  ['Cable Crunch', 'Core'],
]
